# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: DUT AutoSignIn

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 45 18 * * *  # cron time 和北京时间相互转换需要考虑一下

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Do library Reservation
      run: |
        sudo cp -p ./driver/linux/chromedriver /usr/bin   # 运行时候讲
        chmod -R 777 /usr/bin/chromedriver
        python ./src/run_actions.py
      env:
        STUID: ${{ secrets.STUID }}
        PW: ${{ secrets.PW }}
        RUN_ENV: 'linux' # 运行环境 默认为linux
        # MAIL_NOTICE: ${{ secrets.MAI_NOTICE }}
        # MAILBOX: ${{ secrets.MAILBOX }}
